/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pendaftaran;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;

/**
 *
 * @author Swift 3
 */
public class Form_Pelatihan extends javax.swing.JFrame {
    private Connection conn = new koneksi().connect();
    private DefaultTableModel tabmode;
    /**
     * Creates new form Form_Pelatihan
     */
    
    
    protected void datatable() {
        Object[] Baris = {"ID", "Jenis Pelatihan", "Nama Pelatihan", "Tempat Pelatihan", "Metode Pelatihan", "Nama Peneliti"};
        tabmode = new DefaultTableModel(null, Baris);
        tabelPelatihan.setModel(tabmode);
        String sql = "SELECT * FROM pelatihan";
        try {
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while(hasil.next()) {
                String a = hasil.getString("id");
                String b = hasil.getString("jenisPelatihan");
                String c = hasil.getString("namaPelatihan");
                String d = hasil.getString("tempatPelatihan");
                String e = hasil.getString("metodePelatihan");
                String f = hasil.getString("namaPeneliti");
                
                String[] data = {a,b,c,d,e,f};
                tabmode.addRow(data);
            }
        } catch (Exception e) {
            
        }
        
    }
    
    public Form_Pelatihan() {
        initComponents();
        datatable();
    }
    
    protected void kosong() {
        tid.setText("");
        namaPelatihan.setText("");
        tempatPelatihan.setText("");
        metodePelatihan.setSelectedItem("");
        namaPeneliti.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        judul = new javax.swing.JLabel();
        jenis = new javax.swing.JLabel();
        tambahan = new javax.swing.JLabel();
        tambahan2 = new javax.swing.JLabel();
        tempat = new javax.swing.JLabel();
        metode = new javax.swing.JLabel();
        jenisPelatihan = new javax.swing.JComboBox<>();
        namaPelatihan = new javax.swing.JTextField();
        namaPeneliti = new javax.swing.JTextField();
        metodePelatihan = new javax.swing.JComboBox<>();
        bnext = new javax.swing.JButton();
        bedit = new javax.swing.JButton();
        bdelete = new javax.swing.JButton();
        bcancel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelPelatihan = new javax.swing.JTable();
        metode1 = new javax.swing.JLabel();
        tempatPelatihan = new javax.swing.JTextField();
        tid = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        judul.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        judul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judul.setText("FORM PELATIHAN");
        getContentPane().add(judul, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 227, 49));

        jenis.setText("Jenis Pelatihan / Kegiatan kami");
        getContentPane().add(jenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, 20));

        tambahan.setText("Tambahkan Nama Pelatihan");
        tambahan.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(tambahan, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 211, -1, 20));

        tambahan2.setText("yang diajukan Bapak / Ibu");
        tambahan2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(tambahan2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, 20));

        tempat.setText("Tempat Pelatihan / Kegiatan");
        getContentPane().add(tempat, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, -1, -1));

        metode.setText("Nama Peneliti");
        getContentPane().add(metode, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, -1, -1));

        jenisPelatihan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pelatihan Analisis Kebijakan Kesehatan", "Pelatihan Rencana Strategi Bisnis Rumah Sakit", "Pelatihan Kepemimpinan Bagi Kepala Unit/Instalasi Rumah Sakit", "Pelatihan Keselamatan Pasien & Manajemen Resiko di Rumah Sakit", "Pelatihan Clinical Pathway", "Pelatihan Monitoring & Evaluasi Program Kesehatan", "Pelatihan Manajemen Lean", "Pelatihan Regulatory Impact Assessment", "Pelatihan Pemanfaatan Data Rumah Sakit", "Pelatihan Peningkatan Kapasistas & Kapabilitas Perencanaan Kesehatan Berbasis Hasil Pemantauan dan Evaluasi Program Bagi Manajemen Program", "Pelatihan Capacity Building", "Pelatihan Sistem Informasi Rumah Sakit", "Pelatihan Koder Rumah Sakit", "Pelatihan Unit Cost Layanan RS", "Pelatihan Akreditasi Rumah Sakit", "Pelatihan Mutu Rumah Sakit", "Pelatihan Service Excellent", "Pelatihan Strategic & LO", "Lainnya .." }));
        getContentPane().add(jenisPelatihan, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, 482, -1));
        getContentPane().add(namaPelatihan, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 482, 42));
        getContentPane().add(namaPeneliti, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 380, 482, -1));

        metodePelatihan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Online", "Offline", "Hybrid", "Onsite" }));
        metodePelatihan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                metodePelatihanActionPerformed(evt);
            }
        });
        getContentPane().add(metodePelatihan, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 340, 225, -1));

        bnext.setText("NEXT");
        bnext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnextActionPerformed(evt);
            }
        });
        getContentPane().add(bnext, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, 100, 20));

        bedit.setText("EDIT");
        bedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beditActionPerformed(evt);
            }
        });
        getContentPane().add(bedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 420, 100, -1));

        bdelete.setText("DELETE");
        bdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdeleteActionPerformed(evt);
            }
        });
        getContentPane().add(bdelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 420, 100, -1));

        bcancel.setText("CANCEL");
        bcancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcancelActionPerformed(evt);
            }
        });
        getContentPane().add(bcancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 420, 100, -1));

        tabelPelatihan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelPelatihan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelPelatihanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelPelatihan);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 480, 750, 90));

        metode1.setText("Metode Pelatihan yang diajukan");
        getContentPane().add(metode1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, -1, -1));
        getContentPane().add(tempatPelatihan, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, 482, -1));
        getContentPane().add(tid, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, 210, -1));

        setSize(new java.awt.Dimension(881, 635));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bcancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcancelActionPerformed
        // TODO add your handling code here:
         Menubar tugas = new Menubar();
         tugas.setVisible(true);
         this.setVisible(false);
    }//GEN-LAST:event_bcancelActionPerformed

    private void bnextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnextActionPerformed
        // TODO add your handling code here:
        String sql = "INSERT INTO pelatihan VALUES (?,?,?,?,?,?)";
        
        try {
            
            PreparedStatement stat = conn.prepareStatement(sql);
            
            int max = 9999999;
            int min = 1000000;
            int range = max - min + 1;
            
            int rand = (int)(Math.random() * range) + min;
            
            stat.setString(1, "PemVis" + Integer.toString(rand) + "ID");
            stat.setString(2, jenisPelatihan.getSelectedItem().toString()); 
            stat.setString(3, namaPelatihan.getText());          
            stat.setString(4, tempatPelatihan.getText());
            stat.setString(5, metodePelatihan.getSelectedItem().toString()); 
            stat.setString(6, namaPeneliti.getText());
            
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
            datatable();
            
            Form_Proses tugas = new Form_Proses();
            tugas.setVisible(true);
            this.setVisible(false);
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null,"Data Gagal Disimpan " + e);
        }
    }//GEN-LAST:event_bnextActionPerformed

    private void metodePelatihanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_metodePelatihanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_metodePelatihanActionPerformed

    private void tabelPelatihanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelPelatihanMouseClicked
        // TODO add your handling code here:
        
        int bar = tabelPelatihan.getSelectedRow();
        String a = tabmode.getValueAt(bar, 0).toString();
        String b = tabmode.getValueAt(bar, 1).toString();
        String c = tabmode.getValueAt(bar, 2).toString();
        String d = tabmode.getValueAt(bar, 3).toString();
        String e = tabmode.getValueAt(bar, 4).toString();
        String f = tabmode.getValueAt(bar, 5).toString();
        
        tid.setText(a);
        jenisPelatihan.setSelectedItem(b);
        namaPelatihan.setText(c);
        tempatPelatihan.setText(d);
        metodePelatihan.setSelectedItem(e);
        namaPeneliti.setText(f);
    }//GEN-LAST:event_tabelPelatihanMouseClicked

    private void beditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beditActionPerformed
            
        try {
            String sql = "UPDATE pelatihan SET jenisPelatihan = ?, namaPelatihan = ?, tempatPelatihan = ?, metodePelatihan = ?, namaPeneliti = ? where id = '" + tid.getText() + "'";
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, jenisPelatihan.getSelectedItem().toString());
            stat.setString(2, namaPelatihan.getText());
            stat.setString(3, tempatPelatihan.getText());
            stat.setString(4, metodePelatihan.getSelectedItem().toString());
            stat.setString(5, namaPeneliti.getText());
            
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil Diubah");
            kosong();
            tid.requestFocus();
            datatable();
            
        }catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Data Gagal Diubah, " + e);
        }
    }//GEN-LAST:event_beditActionPerformed

    private void bdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdeleteActionPerformed
          // TODO add your handling code here:
          int ok = JOptionPane.showConfirmDialog(null, "Hapus", "Konfirmasi Dialog", JOptionPane.YES_NO_CANCEL_OPTION);
            if (ok == 0) {
            String sql = "DELETE FROM pelatihan WHERE id = '" + tid.getText() +"'";
            try {
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
                kosong();
                tid.requestFocus();
                datatable();
            }catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Data Gagal Dihapus, " + e);
            }
        }
    }//GEN-LAST:event_bdeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Pelatihan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Pelatihan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Pelatihan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Pelatihan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Pelatihan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bcancel;
    private javax.swing.JButton bdelete;
    private javax.swing.JButton bedit;
    private javax.swing.JButton bnext;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jenis;
    private javax.swing.JComboBox<String> jenisPelatihan;
    private javax.swing.JLabel judul;
    private javax.swing.JLabel metode;
    private javax.swing.JLabel metode1;
    private javax.swing.JComboBox<String> metodePelatihan;
    private javax.swing.JTextField namaPelatihan;
    private javax.swing.JTextField namaPeneliti;
    private javax.swing.JTable tabelPelatihan;
    private javax.swing.JLabel tambahan;
    private javax.swing.JLabel tambahan2;
    private javax.swing.JLabel tempat;
    private javax.swing.JTextField tempatPelatihan;
    private javax.swing.JTextField tid;
    // End of variables declaration//GEN-END:variables
}
